language: node_js
node_js:
    - 0.12

branches:
  only:
    - master

before_script:
  - npm install

script:
  - npm run build

after_success:
  - bash ./bin/deploy.sh

env:
  global:
  - GH_REF: github.com/kamataryo/jyoko.git
  - secure: "UeUO/vue29svGLatR5zQtkUdL+04lZ+jQLlLc8+/BxcBmvGp+tC4dCLyDoZi6sKgBBkeooMSNbydFgSeSwheSXIwmYfOfZNRo8QlDdZLQuTURg0Twqeej3FMHrjBgwooG8jYRJHf4//twlsDmvee6VKbuVt06axDfRKthGdIak08XG2VUSthVM2GR9rgHEPxoY+BhRFE+9/Ipm0D73fcIXJcs9mOo0WcpctATPMImi91w66E6l/mrdsBxnJsF5qksvSdKvqa00bUnwurAcZHeMz5EA8ACJAKCHCfYBH6Cov4u7DB0bOVpHwjE4E1v35rG4waffClVB8WPfpvyCAc6yp4h91FyRjICS6tIC5wdOvzbVei4hD50SgYhKxcW0rgMbPq4+K8I4kBCDPVFPbPavllESpVe8X1l36F7WwfFd+g0HUpI5gQ+zk7AbqjGq1OVO1kgDV3bcEjgfyeepVqYKTnHq6spFx3M2IkRpa9kKw6WkKg1MEKGec8Ux6skg5XQmJ9H7+hK/HP8U3kGr2ZhahaKrUyeuJESWIMNf4h50awckaFCiFQFE9QObYJBScErVNlNuL8i3OggyJWT8aVJSizU5FMjOFHI/zw7PJvH5x7fQUL5m1t0uW6ZHYtPSi9zjpF6PSds/lzDYGgQW7s2Ly12ZBnlXeQBCdEiVeHL8g="
